server:
  port: 8080

spring:
  application:
    name: insurance-quote-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
    aws:
      region:
        static: sa-east-1
      stack:
        auto: false
      credentials:
        access-key: admin
        secret-key: admin
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m

catalog-service:
  url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
#  metrics:
#    export:
#      prometheus:
#        enabled: true

logging:
  level:
    root: INFO
    br.com.desafio.insurance: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

cloud:
  aws:
    region:
      static: sa-east-1
    stack:
      auto: false
    credentials:
      access-key: admin
      secret-key: admin
    dynamodb:
      endpoint: ${CLOUD_AWS_DYNAMODB_ENDPOINT:http://localhost:4566}
      table:
        name: insurance-quotes
    fila:
      insurance-quote-received: ${CLOUD_AWS_FILA_INSURANCE_QUOTE_RECEIVED:http://localhost:4566/000000000000/insurance-quote-received}
      insurance-policy-created: ${CLOUD_AWS_FILA_INSURANCE_POLICY_CREATED:http://localhost:4566/000000000000/insurance-policy-created}

aws:
  region: sa-east-1
  accessKey: admin
  secretKey: admin
  sqs:
    queue-url: ${CLOUD_AWS_FILA_INSURANCE_QUOTE_RECEIVED:http://localhost:4566/000000000000/insurance-quote-received}
    endpoint: ${AWS_SQS_ENDPOINT:http://localhost:4566}
