spring.application.name=insurance-quote-service

spring.cache.type=simple
spring.cache.caffeine.spec=expireAfterWrite=10m

# Catalog API URL
catalog-service.url=http://localhost:8080/mock/catalog

# Feign Configuration
feign.client.config.default.read-timeout=5000
feign.client.config.default.connect-timeout=3000

# AWS Configuration
aws.dynamodb.endpoint=
aws.dynamodb.region=sa-east-1
aws.dynamodb.table.name=insurance-quotes
aws.sqs.endpoint=http://localhost:4566
aws.sqs.region=sa-east-1
aws.sqs.queue.insurance-quote-received=http://localhost:4566/000000000000/insurance-quote-received
aws.sqs.queue.insurance-policy-created=http://localhost:4566/000000000000/insurance-policy-created
